version: 1.0.{build}
image: Visual Studio 2019
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/Microservices.Boilerplate/Microservices.Boilerplate.csproj --verbosity m
  - cmd: dotnet tool install --global Codecov.Tool
build_script:
  - cmd: dotnet build ./src/Microservices.Boilerplate/Microservices.Boilerplate.csproj --verbosity m
after_build:
  - cmd: dotnet pack ./src/Microservices.Boilerplate/Microservices.Boilerplate.csproj /p:Version=%APPVEYOR_BUILD_VERSION%
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./src/Microservices.BoilerplateTests/Microservices.BoilerplateTests.csproj --verbosity m
  - cmd: dotnet test ./src/Microservices.BoilerplateTests/Microservices.BoilerplateTests.csproj /p:CollectCoverage=true
  - codecov -f ./src/Microservices.BoilerplateTests/coverage.json -t 0e2b45e7-adf5-41e9-96ea-38eeb339d5a9
artifacts:
  - path: '**\*.nupkg'
deploy: off
