version: 1.0.{build}
image: Visual Studio 2019
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/Microservices.Boilerplate/Microservices.Boilerplate.csproj --verbosity m
  - cmd: dotnet tool install -g coveralls.net
build_script:
  - cmd: dotnet build ./src/Microservices.Boilerplate/Microservices.Boilerplate.csproj --verbosity m
after_build:
  - cmd: dotnet pack ./src/Microservices.Boilerplate/Microservices.Boilerplate.csproj /p:Version=%APPVEYOR_BUILD_VERSION%
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./src/Microservices.BoilerplateTests/Microservices.BoilerplateTests.csproj --verbosity m
  - cmd: dotnet test ./src/Microservices.BoilerplateTests/Microservices.BoilerplateTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - cmd: cd src/Microservices.BoilerplateTests
  - cmd: echo %APPVEYOR_REPO_COMMIT%
  - cmd: echo %APPVEYOR_REPO_BRANCH%
  - cmd: echo %APPVEYOR_REPO_COMMIT_AUTHOR%
  - cmd: echo %APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL%
  - cmd: echo %APPVEYOR_REPO_COMMIT_MESSAGE%
  - cmd: echo %APPVEYOR_JOB_ID%
  - cmd: csmacnz.Coveralls --opencover --input coverage.opencover.xml --repoToken JGmTjpDKd24Cvz8znuH8wQa3QrTQQyOlB --commitId %APPVEYOR_REPO_COMMIT% --commitBranch %APPVEYOR_REPO_BRANCH% --commitAuthor %APPVEYOR_REPO_COMMIT_AUTHOR% --commitEmail %APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL% --commitMessage %APPVEYOR_REPO_COMMIT_MESSAGE% --jobId %APPVEYOR_JOB_ID%
artifacts:
  - path: '**\*.nupkg'
deploy: off
